/*
 * Main_Rabin.java
 *
 * Created on 15 Сентябрь 2008 г., 22:33
 */

package rabin;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.swing.JOptionPane;

/**
 *
 * @author  MozEvil
 */
public class Main_Rabin extends javax.swing.JFrame {

    /** Creates new form Main_Rabin */
    public Main_Rabin() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        label3 = new java.awt.Label();
        textField1 = new java.awt.TextField();
        textArea1 = new java.awt.TextArea();
        jButton5 = new javax.swing.JButton();
        textField2 = new java.awt.TextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Rabin EPt Edition");

        jButton1.setText("p");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });

        jButton2.setText("q");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton2MousePressed(evt);
            }
        });

        jButton3.setText("Зашифровать");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton3MousePressed(evt);
            }
        });

        jButton4.setText("Расшифровать");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton4MousePressed(evt);
            }
        });

        label1.setText("=");

        label2.setText("=");

        label3.setText("=");

        textField1.setText("nu postavte emu zachet !");

        jButton5.setText("n");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton5MousePressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2)
                            .addComponent(jButton1)
                            .addComponent(jButton5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 613, Short.MAX_VALUE)
                            .addComponent(label2, javax.swing.GroupLayout.DEFAULT_SIZE, 613, Short.MAX_VALUE)
                            .addComponent(label1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 613, Short.MAX_VALUE)))
                    .addComponent(textArea1, javax.swing.GroupLayout.DEFAULT_SIZE, 662, Short.MAX_VALUE)
                    .addComponent(textField1, javax.swing.GroupLayout.DEFAULT_SIZE, 662, Short.MAX_VALUE)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(textField2, javax.swing.GroupLayout.DEFAULT_SIZE, 662, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5)
                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textArea1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
// генерим p
    do{
        p1 = getRandTestFerma(64);
        p = (p1.multiply(BigInteger.valueOf(4))).add(BigInteger.valueOf(3));    
        label1.setText("= " + p); 
    }while (TestFerma(p, 64) == false);
}//GEN-LAST:event_jButton1MousePressed
private void jButton2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MousePressed
// генерим q
    do{
        q1 = getRandTestFerma(64);
        q = (q1.multiply(BigInteger.valueOf(4))).add(BigInteger.valueOf(3));    
        label2.setText("= "+q); 
    }while (TestFerma(q, 64) == false);  
}//GEN-LAST:event_jButton2MousePressed
private void jButton3MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MousePressed
// шифруем
    try{
        textField2.setText("");
        textArea1.setText("");       
        String textLC = textField1.getText().toLowerCase();
        char[] buf = textLC.toCharArray();         
        OT = new int[buf.length]; // OT - это открытый текст в числовом представление
        
        // переводим символы в числа 
        for (int i=0; i<buf.length; i++)
            for (int j=0; j<Alf.length; j++)       
                if (buf[i] == Alf[j])
                    OT[i] = j;
        
        // шифруем 
        ST = new BigInteger[OT.length];
        for (int i=0; i<OT.length; i++){
            ST[i] = (BigInteger.valueOf(OT[i]).pow(2)).mod(n); // OT^2  mod n
            textArea1.setText(textArea1.getText() + ST[i]);        
        }   
    
    } catch(Exception e){
        JOptionPane.showMessageDialog(null, e, "Error", 0);
    } 
}//GEN-LAST:event_jButton3MousePressed
private void jButton4MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MousePressed
// расшифровываем
    try{        
        X = new int[ST.length];
        S1 = new BigInteger[ST.length];
        S2 = new BigInteger[ST.length];
        Sqq = new BigInteger[ST.length];
        Spp = new BigInteger[ST.length];
        BigInteger Xbuf1, Xbuf2, Xbuf3, Xbuf4;
        String OTout = "";
        
        for (int i=0; i<ST.length; i++){
            S1[i] = ST[i].modPow((p1.add(BigInteger.valueOf(1))), p);  // S1 = (ST^(p1-1)) mod p   
            S2[i] = ST[i].modPow((q1.add(BigInteger.valueOf(1))), q);  // S2 = (ST^(q1-1)) mod q
        }
   
        BigInteger qInv = q.modInverse(p);  // обратный елемент q по модулю p
        BigInteger pInv = p.modInverse(q);  // обратный елемент p по модулю q

        BigInteger qq = q.multiply(qInv);  // q умножить на обратный елемент q 
        BigInteger pp = p.multiply(pInv);  // p умножить на обратный елемент p

        for (int i=0; i<ST.length; i++){
            Sqq[i] = S1[i].multiply(qq);  // S1*qq
            Spp[i] = S2[i].multiply(pp);  // S2*pp
        }

        // щитаем корни (4 корня) и выбираем тот который нам подходит
        for (int i=0; i<ST.length; i++){
            Xbuf1 = (Sqq[i].add(Spp[i])).mod(n);            
            Xbuf2 = (Sqq[i].subtract(Spp[i])).mod(n);       
            Xbuf3 = (Spp[i].subtract(Sqq[i])).mod(n);       
            Xbuf4 = ((Sqq[i].add(Spp[i])).negate()).mod(n);
            
            if (Xbuf1.intValue() == OT[i])
                X[i] = Xbuf1.intValue();
            if (Xbuf2.intValue() == OT[i])
                X[i] = Xbuf2.intValue();
            if (Xbuf3.intValue() == OT[i])
                X[i] = Xbuf3.intValue();
            if (Xbuf4.intValue() == OT[i])
                X[i] = Xbuf4.intValue();            
        }
        //переводим полученное сообщение из цифрового вида в символьный
        for (int i=0; i<X.length; i++){
            for (int j=0; j<Alf.length; j++){       
                if (X[i] == j)
                    OTout = OTout + Alf[j];
            }
        }
        
        // выводим полученное расшифрованное сообщение на экран
        textField2.setText(""+OTout);
        
        
    } catch(Exception e){
        JOptionPane.showMessageDialog(null, e, "Error", 0);
    } 
}//GEN-LAST:event_jButton4MousePressed

private void jButton5MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MousePressed
// n = p*q
    n = q.multiply(p);          
    label3.setText("= "+n);
}//GEN-LAST:event_jButton5MousePressed

    
    
BigInteger getRand(int bit){ //получаем рандомное bit-битное НЕ ЧЕТНОЕ число      
    BigInteger sum = BigInteger.valueOf(2).pow(bit-1); // т.к. 1-й бит = 1 всегда           
    for( int i=1; i<(bit-1); i++)  // щитаем число
        sum = sum.add(BigInteger.valueOf((int)Math.round(Math.random())).multiply(BigInteger.valueOf(2).pow(bit-i-1)));                                                
    return sum.add(BigInteger.valueOf(1)); // добавляем 1 т.к. последний бит = 1 всегда      
}
BigInteger getRandA(int bit){
    BigDecimal min = BigDecimal.valueOf(2).pow(bit-1);
    min = min.multiply(BigDecimal.valueOf(Math.random())); // min = min*[0,1)
    return min.toBigInteger();
}    
boolean TestFerma(BigInteger n, int bit){
    for (int i=1; i<=50; i++){
        if(getRandA(bit).modPow(n.subtract(BigInteger.valueOf(1)),n).equals(BigInteger.valueOf(1)))                
            continue;            
        else
            return false;
    }
    return true;
}    
BigInteger getRandTestFerma(int bit){
    BigInteger nz;
    do nz = getRand(bit);    
    while (TestFerma(nz, bit) == false);
    return nz;
}    


    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_Rabin().setVisible(true);
            }
        });
    }

    
    private char[] Alf = {' ','0','1','2','3','4','5','6','7','8','9',
                              'a','b','c','d','e','f','j','g','h','i',
                              'k','l','m','n','o','p','q','r','s','t',
                              'u','v','w','x','y','z',',','.','!','?',
                              ':',';','-','_','@','#','$','%','^','&',
                              '*','(',')','~','`','|','/','<','>','+',
                              '[',']','{','}','\\'};
    private int[] OT, X;
    private BigInteger[] ST, S1, S2, Sqq, Spp;                            
    private BigInteger p, p1, q, q1, n;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private java.awt.Label label1;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.TextArea textArea1;
    private java.awt.TextField textField1;
    private java.awt.TextField textField2;
    // End of variables declaration//GEN-END:variables

}
