/*
 * NewJFrame.java
 *
 * Created on 13 Октябрь 2008 г., 17:36
 */

package javaapplication10;

import java.util.Random;
import javax.swing.JOptionPane;

/**
 *
 * @author  MozEvil
 */
public class NewJFrame extends javax.swing.JFrame {

    /** Creates new form NewJFrame */
    public NewJFrame() {
        initComponents();
         p = 65123;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jFileChooser1 = new javax.swing.JFileChooser();
        textField1 = new java.awt.TextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        textField2 = new java.awt.TextField();
        jLabel3 = new javax.swing.JLabel();
        textField3 = new java.awt.TextField();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        list1 = new java.awt.List();
        list2 = new java.awt.List();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jFrame1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textField1.setText("235");

        jLabel1.setText("m = ");

        jLabel2.setText("n = ");

        textField2.setText("5");

        jLabel3.setText("k = ");

        textField3.setText("3");

        jButton1.setText("Разделить секрет");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setText("Восстановить");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        jButton3.setText("+");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jButton4.setText("Clear All");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        jButton5.setText("-");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(list2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
                    .addComponent(list1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 365, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textField1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textField2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textField3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(textField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(textField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(list1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton5)
                    .addComponent(jButton4)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(list2, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
    // разделить секрет

try{    
    list1.removeAll();
    
    m = Integer.parseInt(textField1.getText());
    n = Integer.parseInt(textField2.getText());
    k = Integer.parseInt(textField3.getText());
    BufP = new String[n];
    mat = new int[n][k];
    x = new int[k];
    a = new int[k][n];
    b = new int[n];
    P = new String[n][k];
    
    Random random = new Random(); 
    
    for (int j=0; j<n; j++)        
        for (int i=0; i<k; i++){
            a[i][j] = random.nextInt(p);
            x[i] = random.nextInt(p);
            P[j][i] = "";
        }
    

    for (int i=0; i<n; i++){
        b[i] = (m*a[1][i])%p;
        for (int j=1; j<k; j++)
            b[i] += (x[j]*a[j][i])%p;
    }

    for (int i=0; i<n; i++)
        for (int j=0; j<k; j++)
            P[i][j] += a[j][i];
    
  /*  for (int i=0; i<n; i++){
        BufP[i] = "";
        P[i][k] =""+ b[i]%p; 
        P[i][k+1] =""+ p; 
    }*/
    
    for (int i=0; i<n; i++){
        BufP[i] = "";
        for (int j=0; j<k; j++)
            BufP[i] += P[i][j] + "+";
    BufP[i] = BufP[i].substring(0, BufP[i].length()-1) + "=" + b[i] + "%" + p;
    list1.add(BufP[i]);
    }
    
}
catch(Exception e){
    JOptionPane.showMessageDialog(rootPane, e);
}

    
            
}//GEN-LAST:event_jButton1MouseClicked

private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
// - all 
    list2.removeAll();
    list1.removeAll();
    for (int i=0; i<n; i++)
        list1.add(BufP[i]);
}//GEN-LAST:event_jButton4MouseClicked

private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
// -
    if (list2.getSelectedItem().length() > 0){
        list1.add(list2.getSelectedItem());
        list2.remove(list2.getSelectedItem());
    }
}//GEN-LAST:event_jButton5MouseClicked

private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
// +
    if (list1.getSelectedItem().length() > 0){
        list2.add(list1.getSelectedItem());
        list1.remove(list1.getSelectedItem());
    }
}//GEN-LAST:event_jButton3MouseClicked

private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
// восстановтаь
    String[] ad = list2.getItems();
    if (ad.length >= k){
        double[] A = new double[k*k];
        double[] B = new double[k];
        int l = 0;
        for (int j=0; j<k; j++){
            B[j] = b[j]; 
            for (int i=0; i<k; i++){
                A[l] = Double.parseDouble(P[j][i]);                    
                l++;
            }
        }         
        JOptionPane.showMessageDialog(rootPane, Gauss(A, B));    
    }
    else JOptionPane.showMessageDialog(rootPane, "мало ключей");    
        
}//GEN-LAST:event_jButton2MouseClicked

 
/**
*  возвращает первый корень из матрицы А
*/
double Gauss(double[] A, double[] B){    
int М = B.length;
double X = 0;//некое соотношение
//матрица ответов b отдельна
//прямой ход для матрицы m=4
for(int i=0; i<М; i++)
    for(int j=i+1; j<М; j++){
        X = (A[i+(j*М)]/A[i+(i*М)])%p;
        B[j] -= (B[i]*X)%p;
        for(int l=i; l<М; l++)
            A[l+(j*М)] -= (A[l+(i*М)]*X)%p;        
    }
//обратный ход 
for(int i=М-1; i>=0; i--){
    B[i] = B[i]/A[i+(i*М)];
    for(int j=i-1; j>=0; j--)
        B[j] -= (A[i+(j*М)]*B[i])%p;B[0]=m;    
}
//решения лежат в B[]
return B[0];
}
/*double[] Parser(String st){
    String[] sk = new String[k];
    
    for (int i=0; i<k; i++){
        if (st.charAt(i) == '+')
            sk[i] = st.substring(h, i);
    }
    
    
}

 double Gauss(double[] A, double[] B){    
int m = B.length;
double X = 0;//некое соотношение
//матрица ответов b отдельна
//прямой ход для матрицы m=4
for(int i=0; i<m; i++)
    for(int j=i+1; j<m; j++){
        X = (A[i+j*m]/A[i+i*m])%p;
        B[j] = (B[j]-B[i]*X)%p;
        for(int l=i; l<m; l++)
            A[l+j*m] = (A[l+j*m]-A[l+i*m]*X)%p;        
    }
//обратный ход 
for(int i=m-1; i>=0; i--){
    B[i] = (B[i]/A[i+i*m])%p;
    for(int j=i-1; j>=0; j--)
        B[j] = (B[j]-A[i+j*m]*B[i])%p;//B[0]=m;    
}
//решения лежат в B[]
return B[0];
}
 
 
 
 */


    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }
    private int[][] mat;
    private String[][] P;
    private String[] BufP;
    private int[][] a;
    private int[] x, b;
    private int p, k, n, m;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private java.awt.List list1;
    private java.awt.List list2;
    private java.awt.TextField textField1;
    private java.awt.TextField textField2;
    private java.awt.TextField textField3;
    // End of variables declaration//GEN-END:variables

}
